# ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object.

In [ ]:
#To install NumPy, open the Anaconda Prompt and type:
#> conda install numpy
#Type y for yes when prompted.
#To install NumPy with pip, bring up a terminal window and type:
#$ pip install numpy
#To check:
#import numpy as np
#np.version

In [2]:
import numpy as np
np.version

<module 'numpy.version' from '/usr/local/lib/python3.6/dist-packages/numpy/version.py'>

In [ ]:
z = np.array([1,2,3,4,0])
print(z)

[1 2 3 4 0]


In [14]:
x = np.array([[1,2.0,3.2,4.666,0]])
print(x)

[[1.    2.    3.2   4.666 0.   ]]


In [ ]:
x.dtype

dtype('float64')

In [15]:
x[0,2]

3.2

In [ ]:
x.shape

(1, 5)

In [ ]:
#2D
y=np.array([(1,2,3,5),(4,5,6,7)])
print(y)

[[1 2 3 5]
 [4 5 6 7]]


In [ ]:
y.shape

(2, 4)

In [ ]:
y=y.reshape(4,2)
print(y)

[[1 2]
 [3 5]
 [4 5]
 [6 7]]


Slicing

In [26]:
y=np.array([(1,2,3),(4,5,6)])
print(y)
print(y[0:,1])

[[1 2 3]
 [4 5 6]]
[2 5]


In [36]:
y.ravel()

array([1, 2, 3, 4, 5, 6])

In [35]:
y.shape

(2, 3)

In [27]:
print(y[1,0])

4


Maximum/Minimum

In [29]:
#1-D Array
z = np.array([1,2,3,4,0])
print(z)
print(z.min())
print(z.max())
print(z.sum())

[1 2 3 4 0]
0
4
10


In [30]:
p = np.array([10,0,64,64,7])
print(p)

[10  0 64 64  7]


In [ ]:
p.argmax()

2

In [ ]:
p.argmin()

1

In [ ]:
p.argsort()

array([1, 4, 0, 2, 3])

In [80]:
ar=np.arange(99)

ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [81]:
ar.shape

(99,)

In [ ]:
ar.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
ar.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
ar.shape

(99,)

In [68]:
# 2-D Array
y=np.array([(1,2,3),(4,5,6),(1,7,1),(8,8,3)])
print(y)

print(y[3])

print(y.min())
print(y.max())
print(y.sum())

[[1 2 3]
 [4 5 6]
 [1 7 1]
 [8 8 3]]
[8 8 3]
1
8
49


In [ ]:
y=y.reshape(3,2)
print(y)

In [45]:
print(y.min(axis=0))

[1 2 3]


In [13]:
print(y.max(axis=1))

[3 6]


In [ ]:
print(y.sum(axis=0))
print(y.sum(axis=1))

[ 9 12]
[ 3  7 11]


In [63]:
 y=np.array([(1,2,3),(4,5,6),(7,8,1)])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 1]]


In [64]:
y.argmax(axis=1)

array([2, 2, 1])

In [ ]:
y.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 1])

In [ ]:
y.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [1]])

In [69]:
y.T #Transpose

array([[1, 4, 1, 8],
       [2, 5, 7, 8],
       [3, 6, 1, 3]])

Square Root & Standard Deviation

In [ ]:
print(np.sqrt(y)) #y=np.array([(1,2,3),(4,5,6)])
print(np.std(y))

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
1.707825127659933


Memory

In [74]:
import sys
li = [7,3,0,8]
np_=np.array(li)
print(sys.getsizeof(1)*len(li))
print(np_.itemsize*np_.size)

112
32


# **Operations On Array**

In [ ]:
[1,2,3] + [4,5,6] #list

[1, 2, 3, 4, 5, 6]

In [76]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x)
print(y)
print(x+y)
print(x*y)


[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [3 4 5]]
[[ 2  4  6]
 [ 6  8 10]]
[[ 1  4  9]
 [ 9 16 25]]


In [ ]:
#Ravel:Numpy Array into column
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [22]:
listarray =np.array([(0,8,9),(1,0,0),(0,12,13)])

In [79]:
print(listarray)
np.count_nonzero(listarray)

[[ 0  8  9]
 [ 1  0  0]
 [ 0 12 13]]


5

Intrinsic Numpy Arrays (Arange and Zeros)

In [ ]:
zeros = np.zeros((7,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeros.dtype

dtype('float64')

In [ ]:
c=np.arange(67)
print(c)
np.count_nonzero(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66]


66

In [ ]:
b = np.empty((4,2))
print(b)

[[3.05226641e-316 8.48798317e-313]
 [2.46151512e-312 2.41907520e-312]
 [2.07955588e-312 2.14321575e-312]
 [1.39727685e-306 8.40609360e-284]]
